export const ActionTypes = {
  INPUT_NUMBER: 'INPUT_NUMBER',
  PLUS: 'PLUS',
  MINUS: 'MINUS',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  CLEAR: 'CLEAR',
  EQUAL: 'EQUAL',
  DECIMAL_POINT: 'DECIMAL_POINT',
} as const;
